name: discord
description: Discord bot API.
dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.2
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.8.0
